import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./global_components/header/header";
import NavigationPanel from "./global_components/navigation/navigation_panel";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-slate-900 text-white w-full`}>
        <Header />
        
        <aside className="border-r-2 border-sky-500 px-4 py-2 inline-block h-main-layout w-full lg:w-1/4 relative">
          <NavigationPanel />
        </aside>

        <main className="px-4 py-2 inline-block h-main-layout align-top">
          {children}
        </main>
        
      </body>
    </html>
  );
}
