import { Inter } from 'next/font/google'
import Link from 'next/link';
import global from './global.module.scss';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, params }) {

  const ids = [1,2,4,10];

  console.log('layout params', params);

  const idList = ids.map( (i, index) => {
    return <Link key={`${index}-${i}`} href={`/${i}`}>{i}</Link>
  });

  return (
    <html lang="en">
      <body className={inter.className}>
        <h1>Welcome to the Test</h1>
        <nav className={global.layoutNavigation}>
          <Link href="/">Home</Link>
          <Link href="/list">List</Link>
          <Link href="/lizard">Lizard</Link>
          { idList }
        </nav>
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
